### ISSUE TITLE
Wasted space, console errors and list markers

### ISSUE THREAD

**Issue by badfiles** [qooob/authentic-theme#144]
While Drweb module is running the error counter runs madly.

Google chrome version 43.0.2342.2 dev (64-bit)

![screenshot from 2015-03-28 00 59 34](https://cloud.githubusercontent.com/assets/1597304/6877867/99ff2a22-d4e6-11e4-9028-8ff35a28ef91.png)

**Comment by qooob** [comment]
Please be kind reporting this issue to the module developers. I can't provide support for this third-party module. If they won't react now, they will defenetly react when the theme becomes default.

You can mention the fact that the theme in Webmin package already.

**Comment by badfiles** [comment]
I don't insist, and of course you should not provide support to buggy modules, but experience tells me that such modules can be helpful stress-testing your product.

But the wasted space and strange list markers are still common issue.

**Comment by qooob** [comment]
Yes, I agree. I will take a look at `.length` issue. I can fix it, I think, you're right.

**Comment by qooob** [comment]
And 'wasted' space? Not sure.. It's intentional. Alright, I will make it optional next release.

**Comment by qooob** [comment]
Alright, will make a fix in 11.01. 

Please check in couple of hours and tell me if your Dr.Web module is working better now? 

For so called `wasted` space - well it's intentional. The blank space will go away on smaller screens (try to resize your browser window).

In case you want to have no blank space all the time, use the following code in your custom `styles.css`

```CSS
.col-lg-10 {
    width: 100%;
  }

.col-lg-offset-1 {
    margin-left: 0;
  }
@media(min-width:1200px) {
    .container,
    .container-fluid {
        margin-top: 20px;
    }
}
@media(min-width:1600px) {
    .container,
    .container-fluid {
        margin-top: 20px;
    }
}

```
