### ISSUE TITLE
No solid background at Webmin or Virtualmin top left

### ISSUE THREAD

**Issue by j0bb13** [qooob/authentic-theme#215]
Server: Debian 8 64bit
Client OS/Browser: Windows 8.1, Chrome 44 64bit

The Webmin or Virtualmin which isn't selected in the top left has some opacity, while the selected is solid.
I don't know if this is by design, but I had a "huh, was there something there?" feeling about 3 times when I switched from Virtualmin to Webmin before I figured out there was indeed some text underneath the button I just clicked.

![authentic cosmetic bug](https://cloud.githubusercontent.com/assets/2331451/9027705/0464f058-3960-11e5-81e2-390cafdf5134.png)

**Comment by qooob** [comment]
I see. You can use themse custom extension to make it solid for your self. It will be preserved upon updates.

Got to `Webmin Configuration->Themes` and in the bottom of the screen set custom extension using CSS code:

```CSS
.switch-mins {
    background-color: rgba(40,40,40, 1);
}
```

**Comment by j0bb13** [comment]
Thanks :) I also found that option, I was mostly wondering if it was by design or a small bug.

If it is a bug and is supposed to be solid, these are the values that it won't change the color by setting full opacity:
```css
.switch-mins {
    background-color: rgba(41,46,49, 1)
}
```
