### ISSUE TITLE
Logo in wrong position

### ISSUE THREAD

**Issue by sz00gun** [qooob/authentic-theme#229]
Hi,

is possible to fix logo position, in my case the logo looks like this, which is no good ;)

![logo-auth](https://cloud.githubusercontent.com/assets/7549566/9563561/8f0a27b2-4e7f-11e5-8d6d-ea719b992b46.jpg)

Please advise

**Comment by qooob** [comment]
You can manipulate logo using `._logo` class in theme CSS extensions.

I think (I'm guessing what is no good for you), you need to reset opacity and move it down a bit:

```CSS
._logo {
    opacity: 1;
    margin-bottom: -5px;
}
```
