### ISSUE TITLE
Failure URL field too short

### ISSUE THREAD

**Issue by badfiles** [qooob/authentic-theme#236]
![screenshot from 2015-09-05 13-21-08](https://cloud.githubusercontent.com/assets/1597304/9698842/35c539c4-53d1-11e5-9271-e275beb1f4a1.png)

**Comment by qooob** [comment]
I will fix it next release. So far, add to the CSS extensions something like:

```CSS
input[name="deny"] {
   min-width: 50%;
}
```
