### ISSUE TITLE
CSS for the signin-banner needs amendment to correctly display a banner

### ISSUE THREAD

**Issue by jinesh-choksi** [qooob/authentic-theme#451]
Currently:

- a monospace font is not used
- the banner read from file is displayed as one long string when it should be treated as pre-formatted text
- the width of the form displaying the banner needs to be a little bigger to fit in 80 chars

I've worked around this by creating a **/etc/web/authentic-theme/styles.css** file and in it having the following content:

```CSS
html.session_login, body.session_login, form.session_login, .container.session_login {
    font-family: monospace !important;
    white-space: pre;
    background-color: #f0f0f0;
}

.session_login .form-signin-banner, .session_login .form-signin {
    position: relative;
    max-width: 800px;
    margin: 80px auto 0;
    padding: 30px 30px 40px 30px;
    text-align: center;
    color: #444;
    border: 1px solid #ddd;
    -webkit-border-radius: 4px;
    -moz-border-radius: 4px;
    border-radius: 4px;
    background-color: #fff;
    -webkit-box-shadow: 1px 1px 10px rgba(0,0,0,.15);
    box-shadow: 1px 1px 10px rgba(0,0,0,.15);
}
```
