### ISSUE TITLE
Theme: Can't scoll on ConfigServer Security Firewall (CSF) module

### ISSUE THREAD

**Issue by konceptech** [qooob/authentic-theme#513]
Hi, on latest version of webmin and authentic, it's not possible to scroll on CSF module.

Sometimes possible when you reload the main page, but, if you go into "Firewall Configuration" it is not possible at all.

**Comment by qooob** [comment]
Which version so you consider to be latest?

**Comment by konceptech** [comment]
Webmin 1.801
Authentic Theme 17.84

**Comment by qooob** [comment]
The latest version is 18.03.

Upgrade the theme manually to the version 18.03 as _Webmin_ currently can't handle GitHub connections.

How to upgrade the theme manually see this: https://github.com/qooob/authentic-theme/issues/505

**Comment by konceptech** [comment]
Same thing on 18.03

**Comment by qooob** [comment]
No, it's fixed in 18.03. Make sure to clear browser's cache and restart Webmin.

**Comment by qooob** [comment]
Oh, I could accidentally reproduce no scroll issue in _Firefox_ on some pages of _ConfigServer Security and Firewall_.

Version **18.04** has just been re-uploaded and fixes the issue. Please upgrade!!

**Comment by kreationnext** [comment]
Well done on this one too.

It looks a bit congested now. If you can add some margin to the elements like 3px or so, It will get some pro look. And you can also use the css of the buttons [like green, orange, etc] to give some colors to it.

It will make the buttons more clickable. :D

**Comment by qooob** [comment]
Color and margin/padding to buttons to the main page?

**Comment by kreationnext** [comment]
to the main page: margin/padding.
to all pages: Color for buttons

**Comment by qooob** [comment]
OK, sounds good.

**Comment by qooob** [comment]
@kreationnext Ok, re-install the theme, I have updated version 18.04 with mentioned improvements and some bug fixes!

Like it more this way? ;)

**Comment by kreationnext** [comment]
ya! It looks great! but something I would like to add.
In the main page the general button color is white with grey border and
there is a hover effect too.

You have changed the button color of a few buttons only but not others.
lets take a css[only for csf]
and apply

input[type=submit] {
    color: #fff;
    background: #156BB0;
    border: #999;
    width: 200px;
}
input[type=submit]:hover {
    background: #488BF9;
}

and for small buttons [like edit] you reduce the width [say 60px]

**Comment by kreationnext** [comment]
I only mean for the first page. rest of them are ok

**Comment by qooob** [comment]
Ok, what I can offer you is to add the the following code to Theme Extensions and it will survive updates and apply any CSS you need on CSF - **But you will need to again re-install the theme**, as this feature has just been added for CSF. :laughing: 

```CSS
/* CSF Index page buttons fixed width/style. Start. */
.csf .panel-body > table ~ table.csf-table.table.table-striped.table-condensed[align="center"][border="0"][cellpadding="4"][cellspacing="0"] tbody tr.csf-tr td select,
.csf .panel-body > table ~ table.csf-table.table.table-striped.table-condensed[align="center"][border="0"][cellpadding="4"][cellspacing="0"] tbody tr.csf-tr td input[type="submit"]:not([value="Edit"]) {
    width: 200px  !important;
}
```
