### ISSUE TITLE
Theme: Right slider's notification tab, when hidden, leaves its counter

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#673]
If i set the 'Show notifications tab' to No the notification tab will hide imminently and if i press Dashboard without pressing Save it will still be hidden from the right slider menu but when i open Webmin Themes again it will show Yes but the notification is still hidden. I will also see the red number in the dashboard tab and i can't reset the number. This red number was one of the reason i wanted to disable the notification menu.

Webmin 1.831
Authentic Theme 18.32
Firefox 52.0

**Comment by Sopor-** [comment]
This will show the notification set to Yes but the notification is still hidden.

![picpick-2017 03 10-21 06 13](https://cloud.githubusercontent.com/assets/5789283/23812229/e882b2d8-05d9-11e7-9f79-7baebed1653a.png)

**Comment by qooob** [comment]
That seems like a bug. But I bet it will go away, if you relied the whole page, using Ctrl+R?

**Comment by Sopor-** [comment]
I don't have any red numbers anymore so i have to wait until i get one :)

**Comment by qooob** [comment]
In case you reloaded the page it will not appear anymore, I believe.

**Comment by Sopor-** [comment]
I'm running 4 Webmins and i haven't disable them all yet :)

**Comment by qooob** [comment]
Unless you reload the tab, you shouldn't expect it to work correctly. Only version 20.00+ would be able to do it, I suppose.

**Comment by qooob** [comment]
Yes, I can confirm, that if you disable the _Notification Tab_, then the counter-bubble is not hidden. However, if you save and reload the page, it will be gone. I will make it work correctly, even without a reload, in the next fix.

Question arises, whether should I make the message counter optional (red bubble)? At the same time, I realize, that it represents the key feature of the notification tab. I don't think it's good to add such option.

_Authentic Theme_ is hackable and did you know, that if you go to `Theme Extensions` and add the following to _CSS_ code injector, the red bubble will disappear:

```CSS
.right-side-tab-notification-asterix {
	display: none;
	visibility: hidden;
}
```

You could also hide the counter on the Slider Trigger (Button with the bell):

```CSS
.right-side-tabs-toggler .badge.badge-danger {
	display: none;
	visibility: hidden;
}
```

You could even substitute the bell icon with something else let's say _info-circle_, by adding the following:

```CSS
.right-side-tabs-toggler .fa-bell:before {
    content: "\f006"
}
```
