### ISSUE TITLE
Dashboard - make the second row persistent...

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#945]
I'm running CSF and after the latest dashboard changes the three extra buttons for CSF are hidden below `ConfigServer Security & Firewall 11.05` but if you are a bit lasy and fast it is very easy you press on one of those buttons instead of `ConfigServer Security & Firewall`. In the picture below you can see what happens when it open, the mouse pointer is now on the `search system logs` instead of `ConfigServer Security & Firewall` because it moves when i hover the mouse on it.

![authentic_theme_dropdown](https://user-images.githubusercontent.com/5789283/34058983-50dc6f1a-e1dd-11e7-8634-487793faf243.gif)

So could you make an option for those users that want to have the second row always visible or if you have some other ideas?

**Comment by qooob** [comment]
Probably some other ideas. It's minor and I will get back to it a bit later.

Tomorrow my point is to fix few major bugs and get 19.05 out.

If I have time I'll do it tomorrow.

**Comment by qooob** [comment]
In the future, I will rework it making it more widget looking like.

Meanwhile you can add to custom CSS the following to hide the buttons completely.


```CSS
span[data-id="sysinfo_authentic_theme_version"] .btn-group,
span[data-id="sysinfo_csf_data"] .btn-group {
      display: none;
    }
```
